services:
  - type: web
    name: class-dahom
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn --workers 1 --threads 4 --timeout 120 -b 0.0.0.0:$PORT app:app

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: ADMIN_PASSWORD
        sync: false

      - key: ADMIN_PANEL_PATH
        value: panel

      - key: DATA_DIR
        value: /opt/render/project/src/data

      - key: COOKIE_SECURE
        value: "1"

      - key: ZARINPAL_MERCHANT_ID
        sync: false

      - key: ZARINPAL_SANDBOX
        value: "1"